#!/usr/bin/env ruby

# Trap ^C
Signal.trap('INT') {
  puts "\nCtrl-C detected. Exiting..."
  sleep 1
  exit
}

$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))
require 'heimdall_tools'
require 'heimdall_tools/cli'

HeimdallTools::CLI.start(ARGV)
